# Generated by Django 5.2.7 on 2026-06-12 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('hex_code', models.CharField(help_text='Example: #FFFFFF for white, #000000 for black', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('category', models.CharField(blank=True, choices=[('Select Product', 'Select Product'), ('Ball', 'Ball'), ('Bags & Caps', 'Bags & Caps'), ('Socks', 'Socks'), ('Compressors', 'Compressors'), ('Footwears', 'Footwears'), ('Gloves', 'Gloves'), ('Sport Shoes', 'Sport Shoes'), ('Hoodies', 'Hoodies'), ('Shirts', 'Shirts'), ('Casual Shoes', 'Casual Shoes'), ('Watches', 'Watches'), ('Laptops', 'Laptops'), ('P.Lang', 'Programming Languages')], default='Select Product', max_length=15, null=True)),
                ('sports', models.CharField(blank=True, choices=[('Select Sport', 'Select Sport'), ('Basketball🏀', 'Basketball🏀'), ('Boxing🥊', 'Boxing🥊'), ('Badmington🏸', 'Badmington🏸'), ('Gym⛹', 'Gym⛹'), ('Soccer⚽ ', 'Soccer⚽ '), ('Football🏈⚽', 'Football🏈⚽'), ('Tracks & Fields🏃', 'Tracks & Fields🏃'), ('Rugby🏉', 'Rugby🏉'), ('Volleyball🏐', 'Volleyball🏐'), ('Ping Pong🎾', 'Ping Pong🎾'), ('Cricket', 'Cricket'), ('Lawn Tennis🎾', 'Lawn Tennis🎾')], default='Select Sports', max_length=30, null=True)),
                ('gender_type', models.CharField(blank=True, choices=[('Unisex', 'Unisex'), ('Male', 'Male'), ('Female', 'Female')], default='Unisex', max_length=6, null=True)),
                ('brand_type', models.CharField(blank=True, choices=[('Select', 'Select Condition'), ('New', 'Brand New'), ('Hot', 'Trending'), ('Acube', 'Grade A Used')], default='Select', max_length=7, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/product/')),
                ('is_sales', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('pieces', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('colors', models.ManyToManyField(blank=True, to='store.colors')),
                ('featured_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchandise', to='team.player')),
                ('sizes', models.ManyToManyField(blank=True, to='store.sizes')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='uploads/Product_Gallery/')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_pictures', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Product Image Gallery',
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('review_message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('old_cart', models.CharField(blank=True, max_length=200, null=True)),
                ('same_as_billing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
