# Generated by Django 5.2.7 on 2026-06-12 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('zipcode', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('shipping_address', models.TextField(max_length=20000)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('paypal', 'PayPal')], default='Direct Bank Transfer', max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('shipped', models.BooleanField(default=False)),
                ('date_shipped', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('date_delivered', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.CharField(default='Default', max_length=100)),
                ('size', models.CharField(default='Standard', max_length=100)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_first_name', models.CharField(default='', max_length=200)),
                ('shipping_last_name', models.CharField(default='', max_length=200)),
                ('shipping_address1', models.CharField(max_length=200)),
                ('shipping_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_city', models.CharField(max_length=200)),
                ('shipping_state', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_country', models.CharField(max_length=200)),
                ('shipping_phone', models.CharField(default='', max_length=200)),
                ('shipping_email', models.EmailField(default='', max_length=254, verbose_name='Email Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Address',
            },
        ),
    ]
