# Generated by Django 5.2.7 on 2026-06-12 23:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/Awards/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Awards',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('LE', 'League'), ('TO', 'Tournament'), ('PO', 'Playoffs'), ('QU', 'Qualifiers'), ('EX', 'Exhibition'), ('FR', 'Friendly')], default='LE', max_length=2)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_current_competition', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Competitions',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField(null=True)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='08123456789', max_length=15)),
                ('date_subscribed', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Suscriber',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('is_current_season', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=3, null=True)),
                ('city', models.CharField(default='City', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/Opponent_Photos/')),
                ('competitions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.competition')),
            ],
            options={
                'verbose_name_plural': 'Opponents',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('game_type', models.CharField(choices=[('regular', 'Regular Season'), ('playoff', 'Playoffs'), ('preseason', 'Pre-Season'), ('tournament', 'Tournament'), ('international', 'International')], default='regular', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default='00:00:00')),
                ('indicator', models.CharField(choices=[('vs', 'Home'), ('@', 'Away')], default='vs', max_length=4, null=True)),
                ('team_scores', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('opponent_scores', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('team_win_loss', models.CharField(blank=True, choices=[('Win', 'W'), ('Loss', 'L')], max_length=4, null=True, verbose_name='Team Win/Loss')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='team.competition')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_against', to='team.opponent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='opponents',
            field=models.ManyToManyField(to='team.opponent'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('player_name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveIntegerField()),
                ('position', models.CharField(blank=True, choices=[('SP', 'Select Position'), ('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center'), ('F', 'Forward'), ('G', 'Guard')], default='SP', max_length=2, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('player_image', models.ImageField(blank=True, null=True, upload_to='uploads/Players_Photos/')),
                ('biography', models.TextField(blank=True)),
                ('career_awards', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('award_year', models.CharField(blank=True, default='2026', max_length=4, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('draft_info', models.CharField(blank=True, default='2025: Rd 1, Pk 1 (PYT)', max_length=50, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('is_starter', models.BooleanField(default=True)),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='X(Twitter) URL')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Youtube URL')),
                ('tiktok_link', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_player', to='team.opponent')),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='CareerRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_rec', models.TextField(blank=True)),
                ('rebounds_rec', models.TextField(blank=True)),
                ('assists_rec', models.TextField(blank=True)),
                ('blocks_rec', models.TextField(blank=True)),
                ('steals_rec', models.TextField(blank=True)),
                ('efficiency_rec', models.TextField(blank=True)),
                ('player', models.ForeignKey(help_text='The player associated with career records.', on_delete=django.db.models.deletion.CASCADE, related_name='career_records', to='team.player')),
            ],
            options={
                'verbose_name_plural': 'Players Career Records',
            },
        ),
        migrations.CreateModel(
            name='QuarterlyScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_quarter_1', models.PositiveIntegerField(default=0)),
                ('team_quarter_2', models.PositiveIntegerField(default=0)),
                ('team_quarter_3', models.PositiveIntegerField(default=0)),
                ('team_quarter_4', models.PositiveIntegerField(default=0)),
                ('opponent_quarter_1', models.PositiveIntegerField(default=0)),
                ('opponent_quarter_2', models.PositiveIntegerField(default=0)),
                ('opponent_quarter_3', models.PositiveIntegerField(default=0)),
                ('opponent_quarter_4', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_scores', to='team.game')),
            ],
            options={
                'verbose_name_plural': 'Quarterly Scores',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.season'),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/Sponsors_Photo/')),
                ('website', models.URLField()),
                ('team_sponsors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors_for_this_competition', to='team.competition')),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='uploads/Team_Logos/')),
                ('abbreviation', models.CharField(blank=True, max_length=3, null=True)),
                ('city', models.CharField(max_length=100)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('home_jersey_color', models.CharField(max_length=7)),
                ('away_jersey_color', models.CharField(blank=True, max_length=7)),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='X(Twitter) URL')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Youtube URL')),
                ('tiktok_link', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('competitions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_competition', to='team.competition')),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('game_type', models.CharField(blank=True, choices=[('Regular', 'Regular Season'), ('Playoff', 'Playoffs'), ('Preseason', 'Pre-Season'), ('Tournament', 'Tournament'), ('International', 'International')], default='Regular', max_length=13, null=True)),
                ('w', models.PositiveIntegerField(default=0, verbose_name='W')),
                ('l', models.PositiveIntegerField(default=0, verbose_name='L')),
                ('home_record', models.CharField(default='0-0', max_length=20, verbose_name='HOME')),
                ('away_record', models.CharField(default='0-0', max_length=20, verbose_name='AWAY')),
                ('ppg', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='PPG')),
                ('opp_ppg', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='OPP PPG')),
                ('strk', models.CharField(default='W1', max_length=10, verbose_name='STRK')),
                ('last_5', models.CharField(default='0-0', max_length=10, verbose_name='L5')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='team.competition')),
                ('opponent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standing_stats', to='team.opponent')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standing_stats', to='team.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShotCharts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_title', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('chart_images', models.ImageField(blank=True, null=True, upload_to='uploads/Shot_Chart_Gallery/')),
                ('chart_texts', models.TextField(blank=True, default='', max_length=20000, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_chart', to='team.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_charts', to='team.team')),
            ],
            options={
                'verbose_name_plural': 'Shot Charts',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('starter', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=0)),
                ('field_goal_attempts', models.PositiveIntegerField(default=0)),
                ('field_goal_made', models.PositiveIntegerField(default=0)),
                ('point_3_attempts', models.PositiveIntegerField(default=0)),
                ('point_3_made', models.PositiveIntegerField(default=0)),
                ('point_2_attempts', models.PositiveIntegerField(default=0)),
                ('point_2_made', models.PositiveIntegerField(default=0)),
                ('ft_attempts', models.PositiveIntegerField(default=0)),
                ('ft_made', models.PositiveIntegerField(default=0)),
                ('offensive_rebs', models.PositiveIntegerField(default=0)),
                ('defensive_rebs', models.PositiveIntegerField(default=0)),
                ('blocks', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('steals', models.PositiveIntegerField(default=0)),
                ('turnovers', models.PositiveIntegerField(default=0)),
                ('personal_fouls', models.PositiveIntegerField(default=0)),
                ('game_schedule', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_stats', to='team.game')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponents', to='team.opponent')),
                ('player_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'verbose_name_plural': 'Game Stats',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='team.team'),
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='uploads/Games_Image_Gallery/')),
                ('player_pictures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_pictures', to='team.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_pictures', to='team.team')),
            ],
            options={
                'verbose_name_plural': 'Image Gallery',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('content_top', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/Contents_Photos/')),
                ('content_bottom', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('TEXT', 'Plain Text (Markdown/Basic)'), ('RICH', 'Rich Text (HTML Allowed)'), ('IMG_TEXT', 'Image with Text'), ('IMAGE', 'Image Only')], default='TEXT', max_length=10)),
                ('position', models.CharField(choices=[('TOP', 'Top Header/Announcement Bar'), ('SIDE', 'Sidebar/Rail'), ('MAIN', 'Main Body Section'), ('FOOT', 'Footer'), ('MISC', 'Miscellaneous/Special')], default='MISC', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='team.team')),
            ],
            options={
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.team'),
        ),
        migrations.CreateModel(
            name='TeamNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Team', 'Team News'), ('Hot', 'Hot News'), ('Spotlight', 'Spotlight News'), ('League', 'League News'), ('Base', 'Base')], default='Select News', max_length=15, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/News_Images/')),
                ('heading', models.CharField(blank=True, max_length=80)),
                ('intro', models.TextField(null=True)),
                ('content', models.TextField()),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_news', to='team.competition')),
            ],
            options={
                'verbose_name_plural': 'Team News',
            },
        ),
        migrations.CreateModel(
            name='TeamStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Team President', 'Team President'), ('Chief Executive Officer (CEO)', 'Chief Executive Officer (CEO)'), ('Chief Operating Officer (COO)', 'Chief Operating Officer (COO)'), ('General Manager', 'General Manager (GM)'), ('Sporting Director', 'Sporting Director'), ('Director Of Communication & Media', 'Director Of Communication & Media'), ('Head Coach', 'Head Coach'), ('Assistant Coach', 'Assistant Coach'), ('Scout', 'Scout'), ('Sports Technology & Analytics', 'Spoert Technology & Analytics'), ('Strength and Conditioning Coach', 'Strength and Conditioning Coach'), ('Athletic Trainer', 'Athletic Trainer'), ('Physiotherapist', 'Physiotherapist'), ('Dietitian/Nutritionist', 'Dietitian/Nutritionist'), ('Sports Psychologist', 'Sports Psychologist'), ('Equipment Manager', 'Equipment Manager'), ('Team Secretar', 'Team Secretary'), ('Team Administrator', 'Team Administrator'), ('Player Personnel Assistant', 'Player Personnel Assistant')], default='OWN', max_length=100)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='uploads/Team_Staff_Photos/')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_staff', to='team.team')),
            ],
            options={
                'verbose_name_plural': 'Team Staff',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='game_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='team.venue'),
        ),
        migrations.CreateModel(
            name='CompetitionSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.season')),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championships_won', to='team.team')),
            ],
            options={
                'unique_together': {('season', 'competition')},
            },
        ),
    ]
