# Generated by Django 5.2.7 on 2026-06-12 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballCoachingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('registration_type', models.CharField(choices=[('parent', 'Individual Parent / Guardian'), ('school', 'School / Institution')], default='parent', max_length=10)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('age_or_grade_level', models.CharField(max_length=100)),
                ('num_of_players', models.PositiveIntegerField(default=1, verbose_name='Number of Players / Kids')),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Basketball Registrations',
            },
        ),
        migrations.CreateModel(
            name='CaregiverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Your Name (Primary Contact)')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Recipient Full Name')),
                ('gender_type', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20)),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('self', 'Myself'), ('other', 'Other Relative / Dependent')], max_length=10, verbose_name='Relationship to Recipient')),
                ('recipient_age', models.PositiveIntegerField(default=0)),
                ('primary_medical_condition', models.TextField(help_text='e.g., Stroke recovery, mobility assistance, post-surgery care, elderly monitoring', verbose_name='Primary Medical Condition / Needs')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Special Instructions or Routines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Caregiver Requests',
            },
        ),
        migrations.CreateModel(
            name='KitchenBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('party', 'Social Party / Celebration'), ('sports_event', 'Sports Tournament / Team Catering'), ('corporate', 'Corporate Event'), ('meal_prep', 'Bulk Athlete Meal Prep Contract')], max_length=20)),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('estimated_guests', models.PositiveIntegerField(default=0)),
                ('menu_requirements', models.TextField(help_text='Describe preferred local/intercontinental dishes, buffet or plated setup.', verbose_name='Menu Preferences & Details')),
                ('allergies_restrictions', models.TextField(blank=True, help_text='e.g., Peanut allergies, Vegan, Gluten-Free options required', null=True, verbose_name='Allergies or Dietary Restrictions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kitchen Bookings',
            },
        ),
        migrations.CreateModel(
            name='FitnessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.CharField(choices=[('15+', '15-19'), ('20+', '20-24'), ('25+', '25-29'), ('30+', '30-34'), ('35+', '35-39'), ('40+', '40-44'), ('45+', '45-49'), ('50+', '50+')], default='15+', max_length=20)),
                ('gender_type', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=5)),
                ('fitness_goals', models.CharField(choices=[('weight_loss', 'Weight Loss / Management'), ('muscle_gain', 'Strength & Muscle Hypertrophy'), ('athletic_perf', 'Elite Athletic Performance Tuning'), ('endurance', 'Cardiovascular Conditioning')], max_length=20)),
                ('medical_conditions', models.TextField(blank=True, help_text='State any heart issues, bone/joint pain, high blood pressure, etc.', null=True, verbose_name='Injuries or Medical Conditions')),
                ('current_activity_level', models.CharField(help_text='e.g., Sedentary, 1-2 times a week, Elite Athlete', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fitness Requests',
            },
        ),
    ]
